const Data = [
    {
        id: 0,
        "commonName": "Peace Lily",
        "scientificName": "Spathiphyllum",
        "description": "The Peace Lily is a popular indoor plant known for its elegant white flowers and glossy green leaves. It thrives in low light conditions and is relatively easy to care for.",
        "careRequirements": {
          "light": "Low to medium indirect light",
          "watering": "Keep soil consistently moist, but avoid overwatering",
          "temperature": "Prefers temperatures between 65-80°F",
          "humidity": "Enjoys high humidity levels",
          "soil": "Well-draining potting mix rich in organic matter",
          "fertilization": "Feed monthly with a balanced liquid fertilizer during the growing season",
          "pruning": "Remove dead or yellowing leaves as needed",
          "propagation": "Propagate through division of plant clumps or by rooting stem cuttings",
          "growingZones": "Suitable for USDA Zones 10-11 outdoors, often grown indoors",
          "nativeHabitat": "Native to tropical regions of the Americas and southeastern Asia",
          "uses": "Popular as an indoor decorative plant for homes and offices",
          "toxicity": "Mildly toxic if ingested, can cause irritation",
          "pestsAndDiseases": "Resistant to pests but susceptible to root rot if overwatered"
        },
        "images":'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQPH4_GB7iG_h61yON_K8RZ8XVSda731WEnzgEf84PIIzkZDD6_',
        "type": "Indoor",
        
      },
      {
        id: 1,
        "commonName": "African Violet",
        "scientificName": "Saintpaulia",
        "description": "African Violets are charming indoor plants valued for their delicate, colorful flowers and fuzzy leaves. They are relatively low-maintenance and can bloom year-round when provided.",
        "careRequirements": {
          "light": "Bright, indirect light",
          "watering": "Water when the top inch of soil feels dry, avoid getting water on the leaves",
          "temperature": "Prefers temperatures between 65-75°F",
          "humidity": "Does well in average indoor humidity levels",
          "soil": "Use a well-draining, slightly acidic potting mix",
          "fertilization": "Feed with a balanced fertilizer every 4-6 weeks during the growing season",
          "pruning": "Remove spent flowers and yellowing leaves to encourage blooming",
          "propagation": "Propagate from leaf cuttings or offsets",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to Tanzania",
          "uses": "Commonly grown indoors as a decorative houseplant",
          "toxicity": "Non-toxic to humans and pets",
          "pestsAndDiseases": "Susceptible to aphids, spider mites, and powdery mildew"
        },
        "type": "Indoor",
        "images":'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0NoQXSViS0UfXpbGScTRekcWP0jbkXmkCK2ljNEiLpPTrf0SyeobkQ3IAOk-pWgm_ZDA&usqp=CAU',
      },
      {
        id: 2,
        "commonName": "Orchid",
        "scientificName": "Orchidaceae",
        "description": "Orchids are a diverse family of flowering plants known for their stunning and exotic blooms. They come in various colors, shapes, and sizes, and are prized for their elegance and beauty.",
        "careRequirements": {
          "light": "Bright, indirect light",
          "watering": "Water sparingly, allowing the potting mix to dry slightly between waterings",
          "temperature": "Prefers temperatures between 60-80°F",
          "humidity": "Requires high humidity levels, misting may be necessary",
          "soil": "Use a well-draining orchid potting mix, such as bark or sphagnum moss",
          "fertilization": "Feed with a specialized orchid fertilizer according to label instructions",
          "pruning": "Remove spent flowers and trim damaged or yellowing leaves",
          "propagation": "Propagation is typically done through division or from keiki (baby plants)",
          "growingZones": "Depends on the orchid variety, many are suited for indoor cultivation",
          "nativeHabitat": "Orchids are found in diverse habitats worldwide, from tropical rainforests to arctic tundras",
          "uses": "Valued as ornamental plants, often grown indoors in pots or mounted on slabs",
          "toxicity": "Non-toxic to humans and most pets",
          "pestsAndDiseases": "May be susceptible to aphids, scale insects, and fungal diseases if not properly cared for"
        },
        "type": "Indoor",
        "images":'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQllKzu2rsSpbOIZdGwZvvRgezqtVCVsLBj1xBlJCmy0qjII8Nj',
      },
      {
        id: 3,
        "commonName": "Snake Plant",
        "scientificName": "Sansevieria trifasciata",
        "description": "The Snake Plant, also known as Mother-in-Law's Tongue, is a hardy and low-maintenance indoor plant characterized by its upright sword-like leaves. ",
        "careRequirements": {
          "light": "Tolerates low to bright indirect light, but prefers indirect light",
          "watering": "Allow soil to dry between waterings, as overwatering can cause root rot",
          "temperature": "Thrives in temperatures between 60-85°F",
          "humidity": "Tolerates average indoor humidity levels",
          "soil": "Well-draining potting mix, can tolerate various soil types",
          "fertilization": "Feed sparingly with a balanced liquid fertilizer during the growing season",
          "pruning": "Trim yellowing leaves as needed",
          "propagation": "Propagate through division of rhizomes or leaf cuttings",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to West Africa",
          "uses": "Popular as a low-maintenance indoor plant and for its air-purifying qualities",
          "toxicity": "Mildly toxic if ingested, can cause stomach discomfort",
          "pestsAndDiseases": "Resistant to pests, but may suffer from root rot if overwatered"
        },
        "type": "Indoor",
        "images":'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ8KleJ1SPIUMO-XPblXPVFbOkC_nxZZm8BaP9pezOG3-Q99q2o',
      },
      {
        id: 4,
        "commonName": "Dieffenbachia",
        "scientificName": "Dieffenbachia",
        "description": "Dieffenbachia, also known as Dumb Cane, is a popular indoor plant valued for its attractive foliage and air-purifying qualities. It features large, broad leaves with striking .",
        "careRequirements": {
          "light": "Prefers bright, indirect light",
          "watering": "Keep soil consistently moist during the growing season, but allow it to dry out slightly between waterings in winter",
          "temperature": "Prefers temperatures between 65-75°F",
          "humidity": "Tolerates average indoor humidity levels",
          "soil": "Use a well-draining potting mix rich in organic matter",
          "fertilization": "Feed with a balanced liquid fertilizer monthly during the growing season",
          "pruning": "Trim yellowing leaves and remove dust from the foliage regularly",
          "propagation": "Propagate through stem cuttings",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to tropical regions of Central and South America",
          "uses": "Popular as an indoor decorative plant",
          "toxicity": "Toxic if ingested, can cause irritation and swelling of the mouth and throat",
          "pestsAndDiseases": "Resistant to pests, but may suffer from leaf spots if overwatered"
        },
        "images":'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4AJfMfQaQkBBpk5kja9sOaq9CVVKrrVeluQ&usqp=CAU',
      },
      {
        "id": 5,
        "commonName": "Rose",
        "scientificName": "Rosa",
        "description": "Roses are perennial flowering plants known for their fragrant flowers and thorny stems. They come in a variety of colors, shapes, and sizes, making them popular in gardens and floral arrangements.",
        "careRequirements": {
          "light": "Full sun (at least 6 hours of direct sunlight per day)",
          "watering": "Regular watering, keeping soil consistently moist but well-drained",
          "temperature": "Prefers moderate temperatures (60-75°F)",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining, fertile soil with good organic content",
          "fertilization": "Feed regularly with balanced fertilizer during the growing season",
          "pruning": "Prune in late winter or early spring to promote new growth and shape the plant",
          "propagation": "Easily propagated through cuttings",
          "growingZones": "Depends on the variety, but most are suited for USDA Zones 4-9",
          "nativeHabitat": "Various regions worldwide, including Europe, Asia, and North America",
          "uses": "Popular as ornamental plants in gardens, bouquets, and floral arrangements",
          "toxicity": "Non-toxic to humans, mildly toxic to pets if ingested",
          "pestsAndDiseases": "Susceptible to aphids, thrips, and powdery mildew"
        },
        "type": "Outdoor",
        "images": "https://pardhuherbals.com/wp-content/uploads/2022/10/Rose-Plant.jpg"
      },
      {
        "id":6,
        "commonName": "Marigold",
        "scientificName": "Tagetes",
        "description": "Marigolds are annual flowering plants native to Mexico and Central America. They are known for their vibrant orange and yellow flowers, which bloom profusely throughout the summer and autumn.",
        "careRequirements": {
          "light": "Full sun (at least 6 hours of direct sunlight per day)",
          "watering": "Regular watering, allowing soil to dry out slightly between waterings",
          "temperature": "Prefers warm temperatures, frost-sensitive",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining soil with moderate fertility",
          "fertilization": "Feed occasionally with balanced fertilizer for optimal growth",
          "pruning": "Deadhead spent flowers to promote continuous blooming",
          "propagation": "Easily propagated from seeds or cuttings",
          "growingZones": "Suitable for USDA Zones 2-11, depending on the variety",
          "nativeHabitat": "Native to Mexico and Central America",
          "uses": "Popular as bedding plants, borders, and in containers",
          "toxicity": "Non-toxic to humans, pets, and most livestock",
          "pestsAndDiseases": "Resistant to most pests and diseases, but can be affected by spider mites and aphids"
        },
        "type": "Outdoor",
        "images": "https://cdn.britannica.com/76/118076-050-756CD4F5/French-marigold.jpg"
      },
      {
        "id": 7,
        "commonName": "Sunflower",
        "scientificName": "Helianthus annuus",
        "description": "Sunflowers are iconic annual flowering plants known for their large, daisy-like flowers and tall stems. They are native to North and South America and are cultivated for their seeds, which are a popular snack and a source of oil.",
        "careRequirements": {
          "light": "Full sun (at least 6-8 hours of direct sunlight per day)",
          "watering": "Regular watering, keeping soil consistently moist but not waterlogged",
          "temperature": "Prefers warm temperatures, frost-sensitive",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining soil with good fertility",
          "fertilization": "Feed with balanced fertilizer during the growing season",
          "pruning": "Remove dead or damaged leaves and flowers as needed",
          "propagation": "Easily grown from seeds sown directly in the garden",
          "growingZones": "Suitable for USDA Zones 6-10",
          "nativeHabitat": "North and South America",
          "uses": "Grown for ornamental purposes, seeds, and oil production",
          "toxicity": "Non-toxic to humans and pets",
          "pestsAndDiseases": "Generally resistant to pests and diseases, but can be affected by aphids, caterpillars, and fungal diseases"
        },
        "type": "Outdoor",
        "images": "https://hips.hearstapps.com/hmg-prod/images/sunforest-mix-sunflower-types-1586794598.jpg"
      },
      {
        "id": 8,
        "commonName": "Daisy",
        "scientificName": "Bellis perennis",
        "description": "Daisies are perennial flowering plants characterized by their white petals and yellow centers. They belong to the Asteraceae family and are native to Europe and Asia, though they have been naturalized in many other regions.",
        "careRequirements": {
          "light": "Full sun to partial shade",
          "watering": "Regular watering, allowing soil to dry out slightly between waterings",
          "temperature": "Prefers moderate temperatures, frost-resistant",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining soil with moderate fertility",
          "fertilization": "Feed lightly with balanced fertilizer in spring",
          "pruning": "Deadhead spent flowers to promote continuous blooming",
          "propagation": "Easily propagated from seeds or division",
          "growingZones": "Suitable for USDA Zones 4-9",
          "nativeHabitat": "Europe and Asia",
          "uses": "Popular as bedding plants, borders, and in wildflower gardens",
          "toxicity": "Non-toxic to humans and pets",
          "pestsAndDiseases": "Resistant to most pests and diseases, but can be affected by aphids, slugs, and powdery mildew"
        },
        "type": "Outdoor",
        "images": "https://hips.hearstapps.com/hmg-prod/images/marguerite-daisy-types-1586981163.jpg"
      },
      {
        "id": 9,
        "commonName": "Tulip",
        "scientificName": "Tulipa",
        "description": "Tulips are bulbous perennial flowering plants native to Central Asia. They are known for their cup-shaped flowers in a wide range of colors and patterns. Tulips are popular ornamental plants and are often associated with the Netherlands.",
        "careRequirements": {
          "light": "Full sun to partial shade",
          "watering": "Regular watering, keeping soil evenly moist but not waterlogged",
          "temperature": "Prefers cool to moderate temperatures",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining soil with good fertility",
          "fertilization": "Feed with bulb fertilizer in fall",
          "pruning": "Remove dead flowers and foliage after blooming",
          "propagation": "Propagate from bulbs",
          "growingZones": "Suitable for USDA Zones 3-8",
          "nativeHabitat": "Central Asia",
          "uses": "Popular as garden flowers, cut flowers, and for forcing indoors",
          "toxicity": "Non-toxic to humans, but bulbs can be toxic if ingested",
          "pestsAndDiseases": "Generally resistant to pests and diseases, but can be affected by aphids, slugs, and fungal diseases"
        },
        "type": "Outdoor",
        "images": "https://m.media-amazon.com/images/I/71sQOlkixLL.jpg"
      },
];
export default Data;