
const Data = [
    {
        id: 0,
        "commonName": "Peace Lily",
        "scientificName": "Spathiphyllum",
        "description": "The Peace Lily is a popular indoor plant known for its elegant white flowers and glossy green leaves. It thrives in low light conditions and is relatively easy to care for.",
        "careRequirements": {
          "light": "Low to medium indirect light",
          "watering": "Keep soil consistently moist, but avoid overwatering",
          "temperature": "Prefers temperatures between 65-80°F",
          "humidity": "Enjoys high humidity levels",
          "soil": "Well-draining potting mix rich in organic matter",
          "fertilization": "Feed monthly with a balanced liquid fertilizer during the growing season",
          "pruning": "Remove dead or yellowing leaves as needed",
          "propagation": "Propagate through division of plant clumps or by rooting stem cuttings",
          "growingZones": "Suitable for USDA Zones 10-11 outdoors, often grown indoors",
          "nativeHabitat": "Native to tropical regions of the Americas and southeastern Asia",
          "uses": "Popular as an indoor decorative plant for homes and offices",
          "toxicity": "Mildly toxic if ingested, can cause irritation",
          "pestsAndDiseases": "Resistant to pests but susceptible to root rot if overwatered"
        },
        "images":'https://static.vecteezy.com/system/resources/previews/037/501/544/original/ai-generated-peace-lily-spathiphyllum-wallisii-flower-isolated-on-transparent-background-png.png',
        "type": "Indoor",
        
      },
      {
        id: 1,
        "commonName": "African Violet",
        "scientificName": "Saintpaulia",
        "description": "African Violets are charming indoor plants valued for their delicate, colorful flowers and fuzzy leaves. They are relatively low-maintenance and can bloom year-round when provided.",
        "careRequirements": {
          "light": "Bright, indirect light",
          "watering": "Water when the top inch of soil feels dry, avoid getting water on the leaves",
          "temperature": "Prefers temperatures between 65-75°F",
          "humidity": "Does well in average indoor humidity levels",
          "soil": "Use a well-draining, slightly acidic potting mix",
          "fertilization": "Feed with a balanced fertilizer every 4-6 weeks during the growing season",
          "pruning": "Remove spent flowers and yellowing leaves to encourage blooming",
          "propagation": "Propagate from leaf cuttings or offsets",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to Tanzania",
          "uses": "Commonly grown indoors as a decorative houseplant",
          "toxicity": "Non-toxic to humans and pets",
          "pestsAndDiseases": "Susceptible to aphids, spider mites, and powdery mildew"
        },
        "type": "Indoor",
        "images":'https://png.pngtree.com/png-clipart/20230916/original/pngtree-the-flower-pot-sticker-is-purple-with-purple-flowers-clipart-vector-png-image_12251441.png',
      },
      {
        id: 2,
        "commonName": "Orchid",
        "scientificName": "Orchidaceae",
        "description": "Orchids are a diverse family of flowering plants known for their stunning and exotic blooms. They come in various colors, shapes, and sizes, and are prized for their elegance and beauty.",
        "careRequirements": {
          "light": "Bright, indirect light",
          "watering": "Water sparingly, allowing the potting mix to dry slightly between waterings",
          "temperature": "Prefers temperatures between 60-80°F",
          "humidity": "Requires high humidity levels, misting may be necessary",
          "soil": "Use a well-draining orchid potting mix, such as bark or sphagnum moss",
          "fertilization": "Feed with a specialized orchid fertilizer according to label instructions",
          "pruning": "Remove spent flowers and trim damaged or yellowing leaves",
          "propagation": "Propagation is typically done through division or from keiki (baby plants)",
          "growingZones": "Depends on the orchid variety, many are suited for indoor cultivation",
          "nativeHabitat": "Orchids are found in diverse habitats worldwide, from tropical rainforests to arctic tundras",
          "uses": "Valued as ornamental plants, often grown indoors in pots or mounted on slabs",
          "toxicity": "Non-toxic to humans and most pets",
          "pestsAndDiseases": "May be susceptible to aphids, scale insects, and fungal diseases if not properly cared for"
        },
        "type": "Indoor",
        "images":'https://static.vecteezy.com/system/resources/previews/027/254/707/original/white-orchid-plant-in-a-white-pot-png.png',
      },
      {
        id: 3,
        "commonName": "Snake Plant",
        "scientificName": "Sansevieria trifasciata",
        "description": "The Snake Plant, also known as Mother-in-Law's Tongue, is a hardy and low-maintenance indoor plant characterized by its upright sword-like leaves. ",
        "careRequirements": {
          "light": "Tolerates low to bright indirect light, but prefers indirect light",
          "watering": "Allow soil to dry between waterings, as overwatering can cause root rot",
          "temperature": "Thrives in temperatures between 60-85°F",
          "humidity": "Tolerates average indoor humidity levels",
          "soil": "Well-draining potting mix, can tolerate various soil types",
          "fertilization": "Feed sparingly with a balanced liquid fertilizer during the growing season",
          "pruning": "Trim yellowing leaves as needed",
          "propagation": "Propagate through division of rhizomes or leaf cuttings",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to West Africa",
          "uses": "Popular as a low-maintenance indoor plant and for its air-purifying qualities",
          "toxicity": "Mildly toxic if ingested, can cause stomach discomfort",
          "pestsAndDiseases": "Resistant to pests, but may suffer from root rot if overwatered"
        },
        "type": "Indoor",
        "images":'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ8KleJ1SPIUMO-XPblXPVFbOkC_nxZZm8BaP9pezOG3-Q99q2o',
      },
      {
        id: 4,
        "commonName": "Dieffenbachia",
        "scientificName": "Dieffenbachia",
        "description": "Dieffenbachia, also known as Dumb Cane, is a popular indoor plant valued for its attractive foliage and air-purifying qualities. It features large, broad leaves with striking .",
        "careRequirements": {
          "light": "Prefers bright, indirect light",
          "watering": "Keep soil consistently moist during the growing season, but allow it to dry out slightly between waterings in winter",
          "temperature": "Prefers temperatures between 65-75°F",
          "humidity": "Tolerates average indoor humidity levels",
          "soil": "Use a well-draining potting mix rich in organic matter",
          "fertilization": "Feed with a balanced liquid fertilizer monthly during the growing season",
          "pruning": "Trim yellowing leaves and remove dust from the foliage regularly",
          "propagation": "Propagate through stem cuttings",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to tropical regions of Central and South America",
          "uses": "Popular as an indoor decorative plant",
          "toxicity": "Toxic if ingested, can cause irritation and swelling of the mouth and throat",
          "pestsAndDiseases": "Resistant to pests, but may suffer from leaf spots if overwatered"
        },
        "images":'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRU4MHX6lxNq29lA3k9CaGhFLqI3RC7Cpnl3xPDZgyxJv6Sftx4',
      },
      {
        id:5,
        "commonName": "Boston Fern",
        "scientificName": "Nephrolepis exaltata",
        "description": "The Boston Fern is a classic and popular indoor plant known for its lush, feathery fronds that cascade gracefully from hanging baskets or pots. It thrives in humid environments and adds a touch of greenery to indoor spaces.",
        "careRequirements": {
          "light": "Prefers bright, indirect light but can tolerate lower light conditions",
          "watering": "Keep soil consistently moist, but not waterlogged",
          "temperature": "Thrives in temperatures between 60-75°F",
          "humidity": "Requires high humidity levels, misting may be necessary",
          "soil": "Well-draining potting mix with high organic content",
          "fertilization": "Feed with a balanced liquid fertilizer every 4-6 weeks during the growing season",
          "pruning": "Remove dead or yellowing fronds as needed",
          "propagation": "Propagate through division of the root ball",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to tropical regions of the Americas",
          "uses": "Commonly grown indoors as a decorative houseplant, often in hanging baskets",
          "toxicity": "Non-toxic to humans and pets",
          "pestsAndDiseases": "Susceptible to spider mites, scale insects, and mealybugs"
        },
        "type": "Indoor",
        "images": "https://res.cloudinary.com/patch-gardens/image/upload/c_fill,f_auto,h_840,q_auto:good,w_840/v1539018609/products/boston-fern-8f6ed2.psd"
      },
      {
        id: 6,
        "commonName": "Christmas Cactus",
        "scientificName": "Schlumbergera",
        "description": "The Christmas Cactus is a popular holiday plant known for its colorful flowers that bloom around Christmas time. It is a type of succulent that requires minimal care and can thrive indoors.",
        "careRequirements": {
          "light": "Prefers bright, indirect light",
          "watering": "Water thoroughly when the top inch of soil feels dry, but avoid overwatering",
          "temperature": "Prefers temperatures between 60-70°F",
          "humidity": "Tolerates average indoor humidity levels",
          "soil": "Well-draining potting mix formulated for succulents",
          "fertilization": "Feed with a balanced liquid fertilizer monthly during the growing season",
          "pruning": "Pinch back stems after flowering to encourage bushiness",
          "propagation": "Propagate from stem cuttings",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to Brazil",
          "uses": "Grown indoors as a decorative plant, especially during the holiday season",
          "toxicity": "Non-toxic to humans and pets",
          "pestsAndDiseases": "Generally pest-resistant, but may suffer from root rot if overwatered"
        },
        "type": "Indoor",
        "images": "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-christmas-cactus-schlumbergera-succulent-plant-1-723302_300x@2x.jpg?v=1679749533"
      },
      {
        id: 7,
        "commonName": "Anthurium",
        "scientificName": "Anthurium andraeanum",
        "description": "Anthuriums, also known as Flamingo Flowers or Laceleaf, are tropical plants prized for their stunning, brightly colored flowers and glossy foliage. They are popular as indoor plants and are relatively easy to care for.",
        "careRequirements": {
          "light": "Bright, indirect light",
          "watering": "Keep soil evenly moist, but not waterlogged",
          "temperature": "Prefers temperatures between 65-80°F",
          "humidity": "Requires high humidity levels",
          "soil": "Well-draining potting mix rich in organic matter",
          "fertilization": "Feed with a balanced liquid fertilizer every 4-6 weeks during the growing season",
          "pruning": "Remove spent flowers and yellowing leaves",
          "propagation": "Propagate through division of rhizomes or stem cuttings",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to tropical regions of Central and South America",
          "uses": "Popular as an indoor ornamental plant",
          "toxicity": "Mildly toxic if ingested, can cause irritation",
          "pestsAndDiseases": "Susceptible to aphids, mealybugs, and root rot if overwatered"
        },
        "type": "Indoor",
        "images": "https://cdn.shopify.com/s/files/1/0013/3529/6118/files/Anthurium-x-Utah-Detail.jpg?1000"
      },
      {
        id: 8,
        "commonName": "ZZ Plant",
        "scientificName": "Zamioculcas zamiifolia",
        "description": "The ZZ Plant is a low-maintenance and drought-tolerant indoor plant characterized by its glossy, dark green leaves. It is highly adaptable to a variety of indoor conditions and is an excellent choice for beginner gardeners.",
        "careRequirements": {
          "light": "Tolerates low to bright indirect light, but prefers indirect light",
          "watering": "Allow soil to dry out between waterings, as overwatering can cause root rot",
          "temperature": "Thrives in temperatures between 65-75°F",
          "humidity": "Tolerates average indoor humidity levels",
          "soil": "Well-draining potting mix",
          "fertilization": "Feed sparingly with a balanced liquid fertilizer during the growing season",
          "pruning": "Trim yellowingleaves as needed",
          "propagation": "Propagate through division of rhizomes",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to eastern Africa",
          "uses": "Commonly grown indoors as a decorative plant",
          "toxicity": "Mildly toxic if ingested, can cause stomach discomfort",
          "pestsAndDiseases": "Resistant to pests, but may suffer from root rot if overwatered"
        },
        "type": "Indoor",
        "images": "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1684789715-the_sill-variant-white_gloss-zz_plant.jpg?crop=1xw:0.966xh;center,top&resize=980:*"
      },
      {
        id: 9,
        "commonName": "Pothos",
        "scientificName": "Epipremnum aureum",
        "description": "Pothos, also known as Devil's Ivy, is a popular indoor vine valued for its attractive heart-shaped leaves and easy care requirements. It is versatile and can be grown in various conditions, making it a favorite for indoor spaces.",
        "careRequirements": {
          "light": "Thrives in low to medium indirect light, but can tolerate low light conditions",
          "watering": "Allow soil to dry out between waterings, as overwatering can cause root rot",
          "temperature": "Prefers temperatures between 65-75°F",
          "humidity": "Tolerates average indoor humidity levels",
          "soil": "Well-draining potting mix",
          "fertilization": "Feed with a balanced liquid fertilizer every 4-6 weeks during the growing season",
          "pruning": "Trim back leggy growth to encourage bushiness",
          "propagation": "Easily propagated from stem cuttings in water or soil",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to the Solomon Islands",
          "uses": "Popular as a hanging or climbing plant indoors",
          "toxicity": "Mildly toxic if ingested, can cause stomach discomfort",
          "pestsAndDiseases": "Resistant to pests, but may suffer from root rot if overwatered"
        },
        "type": "Indoor",
        "images":"https://budsnblush.com/cdn/shop/products/SilverSatinPothosBigLeaves_ScindapsusPictus_AirPurifyingPlants.jpg?v=1660209053"
      },
      {
        id: 10,
        "commonName": "Chinese Evergreen",
        "scientificName": "Aglaonema",
        "description": "Chinese Evergreen is a popular indoor plant valued for its attractive foliage and air-purifying qualities. It comes in various cultivars with different leaf patterns and colors, making it a versatile choice for indoor decor.",
        "careRequirements": {
          "light": "Tolerates low to medium indirect light, but prefers indirect light",
          "watering": "Allow soil to dry out slightly between waterings, as overwatering can cause root rot",
          "temperature": "Prefers temperatures between 65-75°F",
          "humidity": "Tolerates average indoor humidity levels",
          "soil": "Well-draining potting mix",
          "fertilization": "Feed with a balanced liquid fertilizer every 4-6 weeks during the growing season",
          "pruning": "Trim yellowing leaves as needed",
          "propagation": "Propagate through division of root ball or stem cuttings",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to tropical regions of Asia",
          "uses": "Popular as an indoor decorative plant",
          "toxicity": "Mildly toxic if ingested, can cause irritation",
          "pestsAndDiseases": "Resistant to pests, but may suffer from root rot if overwatered"
        },
        "type": "Indoor",
        "images": "https://cdn.mos.cms.futurecdn.net/opVxtLDKnSymCc3JruP8GK.jpg"
      },
      {
        id: 11,
        "commonName": "Aloe Vera",
        "scientificName": "Aloe vera",
        "description": "Aloe Vera is a succulent plant valued for its medicinal properties and attractive foliage. It is known for its soothing gel, which is commonly used to treat minor burns and skin irritations.",
        "careRequirements": {
          "light": "Prefers bright, indirect light",
          "watering": "Allow soil to dry out between waterings, as overwatering can cause root rot",
          "temperature": "Thrives in temperatures between 60-75°F",
          "humidity": "Tolerates average indoor humidity levels",
          "soil": "Use a well-draining cactus or succulent potting mix",
          "fertilization": "Feed sparingly with a balanced liquid fertilizer during the growing season",
          "pruning": "Remove spent flower stalks and dead leaves",
          "propagation": "Propagate from offsets or leaf cuttings",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to the Arabian Peninsula",
          "uses": "Valued for its medicinal properties and as an ornamental plant",
          "toxicity": "Mildly toxic if ingested, can cause stomach discomfort",
          "pestsAndDiseases": "Resistant to pests, but may suffer from root rot if overwatered"
        },
        "type": "Indoor",
        "images":"https://media.post.rvohealth.io/wp-content/uploads/2020/09/aloe-vera-732x549-thumbnail.jpg"
      },
      {
        id: 12,
        "commonName": "Jade Plant",
        "scientificName": "Crassula ovata",
        "description": "The Jade Plant, also known as the Money Plant or Friendship Tree, is a popular succulent valued for its attractive and resilient nature. It is believed to bring good luck and prosperity.",
        "careRequirements": {
          "light": "Prefers bright, indirect light",
          "watering": "Allow soil to dry out between waterings, as overwatering can cause root rot",
          "temperature": "Thrives in temperatures between 65-75°F",
          "humidity": "Tolerates average indoor humidity levels",
          "soil": "Use a well-draining cactus or succulent potting mix",
          "fertilization": "Feed with a balanced liquid fertilizer monthly during the growing season",
          "pruning": "Pinch back stem tips to encourage bushiness",
          "propagation": "Propagate from stem or leaf cuttings",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to South Africa",
          "uses": "Popular as a houseplant and for bonsai cultivation",
          "toxicity": "Mildly toxic if ingested, can cause stomach discomfort",
          "pestsAndDiseases": "Resistant to pests, but may suffer from root rot if overwatered"
        },
        "type": "Indoor",
        "images": "https://m.media-amazon.com/images/I/51fehIGF48L._AC_UF1000,1000_QL80_.jpg"
      },
      {
        id: 13,
        "commonName": "Begonia",
        "scientificName": "Begonia",
        "description": "Begonias are a diverse group of flowering plants valued for their colorful flowers and attractive foliage. They come in various forms, including tuberous, fibrous, and rhizomatous, and are popular as both indoor and outdoor plants.",
        "careRequirements": {
          "light": "Prefers bright, indirect light",
          "watering": "Keep soil consistently moist, but not waterlogged",
          "temperature": "Prefers temperatures between 65-75°F",
          "humidity": "Tolerates average indoor humidity levels",
          "soil": "Use a well-draining potting mix rich in organic matter",
          "fertilization": "Feed with a balanced liquid fertilizer every 4-6 weeks during the growing season",
          "pruning": "Remove spent flowers and yellowing leaves",
          "propagation": "Propagate from stem cuttings or leaf cuttings",
          "growingZones": "Depends on the species and variety, but many are suited for indoor cultivation",
          "nativeHabitat": "Native to tropical and subtropical regions worldwide",
          "uses": "Popular as ornamental plants in gardens and indoor spaces",
          "toxicity": "Mildly toxic if ingested, can cause stomach discomfort",
          "pestsAndDiseases": "Susceptible to powdery mildew, aphids, and spider mites"
        },
        "type": "Indoor/Outdoor",
        "images": "https://naturerabbit.in/wp-content/uploads/2018/11/Nature-Rabbit-Begonia-Red-Plant-1.jpg"
      },
      {
        id: 14,
        "commonName": "Kalanchoe",
        "scientificName": "Kalanchoe",
        "description": "Kalanchoes are succulent plants valued for their colorful flowers and thick, fleshy leaves. They are popular as indoor and outdoor plants, especially during the winter months when they produce vibrant blooms.",
        "careRequirements": {
          "light": "Prefers bright, indirect light",
          "watering": "Allow soil to dry out slightly between waterings, as overwatering can cause root rot",
          "temperature": "Thrives in temperatures between 60-85°F",
          "humidity": "Tolerates average indoor humidity levels",
          "soil": "Use a well-draining cactus or succulent potting mix",
          "fertilization": "Feed with a balanced liquid fertilizer monthly during the growing season",
          "pruning": "Remove spent flowers and dead leaves",
          "propagation": "Propagate from stem cuttings or leaf cuttings",
          "growingZones": "Depends on the species and variety, but many are suitable for indoor cultivation",
          "nativeHabitat": "Native to Madagascar and tropical Africa",
          "uses": "Commonly grown indoors as a decorative plant",
          "toxicity": "Mildly toxic if ingested, can cause stomach discomfort",
          "pestsAndDiseases": "Resistant to pests, but may suffer from root rot if overwatered"
        },
        "type": "Indoor/Outdoor",
        "images": "https://rukminim2.flixcart.com/image/850/1000/kwv0djk0/plant-sapling/u/t/f/yes-annual-yes-kalanchoe-plant-indian-flower-1-pagoda-point-original-imag9gdafaytz7gf.jpeg?q=90&crop=false"
      },
      {
        id: 15,
        "commonName": "Bromeliad",
        "scientificName": "Bromeliaceae",
        "description": "Bromeliads are a diverse family of tropical plants valued for their vibrant and long-lasting flowers, as well as their striking foliage. They are popular as indoor and outdoor ornamental plants and are relatively easy to care for.",
        "careRequirements": {
          "light": "Prefers bright, indirect light",
          "watering": "Keep the central cup filled with water and mist the leaves regularly, avoid overwatering the soil",
          "temperature": "Thrives in temperatures between 65-80°F",
          "humidity": "Requires high humidity levels",
          "soil": "Use a well-draining potting mix formulated for epiphytic plants",
          "fertilization": "Feed with a diluted liquid fertilizer monthly during the growing season",
          "pruning": "Trim dead leaves and spent flowers as needed",
          "propagation": "Propagate from offsets produced by the mother plant",
          "growingZones": "Depends on the species and variety, but many are suitable for indoor cultivation",
          "nativeHabitat": "Native to tropical regions of the Americas",
          "uses": "Popular as indoor and outdoor ornamental plants",
          "toxicity": "Non-toxic to humans and pets",
          "pestsAndDiseases": "Generally pest-resistant, but may suffer from fungal diseases if overwatered"
        },
        "type": "Indoor/Outdoor",
        "images": "https://asset.bloomnation.com/c_pad,d_vendor:global:catalog:product:image.png,f_auto,fl_preserve_transparency,q_auto/v1635386596/vendor/2864/catalog/product/2/0/20210824113629_file_6125827d60dad_612582ef2afae._6179a27159724.jpg"
      },
      {
        id: 16,
        "commonName": "Gerbera Daisy",
        "scientificName": "Gerbera jamesonii",
        "description": "Gerbera Daisies are cheerful and colorful flowering plants valued for their large, daisy-like flowers that come in various vibrant hues. They are popular as indoor and outdoor plants and are commonly used in floral arrangements.",
        "careRequirements": {
          "light": "Prefers bright, indirect light",
          "watering": "Keep soil evenly moist, but not waterlogged",
          "temperature": "Prefers temperatures between 65-75°F",
          "humidity": "Tolerates average indoor humidity levels",
          "soil": "Use a well-draining potting mix rich in organic matter",
          "fertilization": "Feed with a balanced liquid fertilizer every 4-6 weeks during the growing season",
          "pruning": "Remove spent flowers and yellowing leaves",
          "propagation": "Propagate from seed or by dividing the clumps",
          "growingZones": "Suitable for outdoor cultivation in USDA Zones 8-11, can be grown indoors",
          "nativeHabitat": "Native to South Africa",
          "uses": "Popular as ornamental plants in gardens and floral arrangements",
          "toxicity": "Non-toxic to humans and pets",
          "pestsAndDiseases": "Susceptible to aphids, spider mites, and powdery mildew"
        },
        "type": "Indoor/Outdoor",
        "images": "https://nurserylive.com/cdn/shop/products/nurserylive-plants-gerbera-red-plant-16968877113484.jpg?v=1634220246"
      },
      {
        id: 17,
        "commonName": "Cyclamen",
        "scientificName": "Cyclamen",
        "description": "Cyclamen is a charming flowering plant known for its uniquely shaped flowers and marbledfoliage. It blooms in the winter months and is popular as an indoor plant for adding color to homes during the colder seasons.",
        "careRequirements": {
          "light": "Prefers bright, indirect light",
          "watering": "Water thoroughly when the top inch of soil feels dry, avoid getting water on the crown of the plant",
          "temperature": "Prefers cool temperatures between 50-65°F",
          "humidity": "Tolerates average indoor humidity levels",
          "soil": "Use a well-draining potting mix",
          "fertilization": "Feed with a balanced liquid fertilizer every 4-6 weeks during the growing season",
          "pruning": "Remove spent flowers and yellowing leaves",
          "propagation": "Propagate from seed or by dividing the tubers",
          "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
          "nativeHabitat": "Native to the Mediterranean region",
          "uses": "Popular as an indoor decorative plant, especially during the winter months",
          "toxicity": "Toxic if ingested, can cause stomach discomfort",
          "pestsAndDiseases": "Susceptible to aphids, spider mites, and gray mold"
        },
        "type": "Indoor",
        "images":"https://imengine.public.prod.dur.navigacloud.com/?uuid=495f6b8c-03d2-5c14-be36-85ffb72df1ef&function=original&type=preview"
      }
    
];
export default Data;