
const Data = [
    {
        "id": 0,
        "commonName": "Rose",
        "scientificName": "Rosa",
        "description": "Roses are perennial flowering plants known for their fragrant flowers and thorny stems. They come in a variety of colors, shapes, and sizes, making them popular in gardens and floral arrangements.",
        "careRequirements": {
          "light": "Full sun (at least 6 hours of direct sunlight per day)",
          "watering": "Regular watering, keeping soil consistently moist but well-drained",
          "temperature": "Prefers moderate temperatures (60-75°F)",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining, fertile soil with good organic content",
          "fertilization": "Feed regularly with balanced fertilizer during the growing season",
          "pruning": "Prune in late winter or early spring to promote new growth and shape the plant",
          "propagation": "Easily propagated through cuttings",
          "growingZones": "Depends on the variety, but most are suited for USDA Zones 4-9",
          "nativeHabitat": "Various regions worldwide, including Europe, Asia, and North America",
          "uses": "Popular as ornamental plants in gardens, bouquets, and floral arrangements",
          "toxicity": "Non-toxic to humans, mildly toxic to pets if ingested",
          "pestsAndDiseases": "Susceptible to aphids, thrips, and powdery mildew"
        },
        "type": "Outdoor",
        "images": "https://png.pngtree.com/png-clipart/20240129/original/pngtree-rose-flower-growing-in-pot-png-image_14177571.png"
      },
      {
        "id":1,
        "commonName": "Marigold",
        "scientificName": "Tagetes",
        "description": "Marigolds are annual flowering plants native to Mexico and Central America. They are known for their vibrant orange and yellow flowers, which bloom profusely throughout the summer and autumn.",
        "careRequirements": {
          "light": "Full sun (at least 6 hours of direct sunlight per day)",
          "watering": "Regular watering, allowing soil to dry out slightly between waterings",
          "temperature": "Prefers warm temperatures, frost-sensitive",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining soil with moderate fertility",
          "fertilization": "Feed occasionally with balanced fertilizer for optimal growth",
          "pruning": "Deadhead spent flowers to promote continuous blooming",
          "propagation": "Easily propagated from seeds or cuttings",
          "growingZones": "Suitable for USDA Zones 2-11, depending on the variety",
          "nativeHabitat": "Native to Mexico and Central America",
          "uses": "Popular as bedding plants, borders, and in containers",
          "toxicity": "Non-toxic to humans, pets, and most livestock",
          "pestsAndDiseases": "Resistant to most pests and diseases, but can be affected by spider mites and aphids"
        },
        "type": "Outdoor",
        "images": "https://www.pngall.com/wp-content/uploads/13/Marigold-PNG-Images.png"
      },
      {
        "id": 2,
        "commonName": "Sunflower",
        "scientificName": "Helianthus annuus",
        "description": "Sunflowers are iconic annual flowering plants known for their large, daisy-like flowers and tall stems. They are native to North and South America and are cultivated for their seeds, which are a popular snack and a source of oil.",
        "careRequirements": {
          "light": "Full sun (at least 6-8 hours of direct sunlight per day)",
          "watering": "Regular watering, keeping soil consistently moist but not waterlogged",
          "temperature": "Prefers warm temperatures, frost-sensitive",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining soil with good fertility",
          "fertilization": "Feed with balanced fertilizer during the growing season",
          "pruning": "Remove dead or damaged leaves and flowers as needed",
          "propagation": "Easily grown from seeds sown directly in the garden",
          "growingZones": "Suitable for USDA Zones 6-10",
          "nativeHabitat": "North and South America",
          "uses": "Grown for ornamental purposes, seeds, and oil production",
          "toxicity": "Non-toxic to humans and pets",
          "pestsAndDiseases": "Generally resistant to pests and diseases, but can be affected by aphids, caterpillars, and fungal diseases"
        },
        "type": "Outdoor",
        "images": "https://atlas-content-cdn.pixelsquid.com/stock-images/sunflower-MNAkl9D-600.jpg"
      },
      {
        "id": 3,
        "commonName": "Daisy",
        "scientificName": "Bellis perennis",
        "description": "Daisies are perennial flowering plants characterized by their white petals and yellow centers. They belong to the Asteraceae family and are native to Europe and Asia, though they have been naturalized in many other regions.",
        "careRequirements": {
          "light": "Full sun to partial shade",
          "watering": "Regular watering, allowing soil to dry out slightly between waterings",
          "temperature": "Prefers moderate temperatures, frost-resistant",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining soil with moderate fertility",
          "fertilization": "Feed lightly with balanced fertilizer in spring",
          "pruning": "Deadhead spent flowers to promote continuous blooming",
          "propagation": "Easily propagated from seeds or division",
          "growingZones": "Suitable for USDA Zones 4-9",
          "nativeHabitat": "Europe and Asia",
          "uses": "Popular as bedding plants, borders, and in wildflower gardens",
          "toxicity": "Non-toxic to humans and pets",
          "pestsAndDiseases": "Resistant to most pests and diseases, but can be affected by aphids, slugs, and powdery mildew"
        },
        "type": "Outdoor",
        "images": "https://hips.hearstapps.com/hmg-prod/images/marguerite-daisy-types-1586981163.jpg"
      },
      {
        "id": 4,
        "commonName": "Tulip",
        "scientificName": "Tulipa",
        "description": "Tulips are bulbous perennial flowering plants native to Central Asia. They are known for their cup-shaped flowers in a wide range of colors and patterns. Tulips are popular ornamental plants and are often associated with the Netherlands.",
        "careRequirements": {
          "light": "Full sun to partial shade",
          "watering": "Regular watering, keeping soil evenly moist but not waterlogged",
          "temperature": "Prefers cool to moderate temperatures",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining soil with good fertility",
          "fertilization": "Feed with bulb fertilizer in fall",
          "pruning": "Remove dead flowers and foliage after blooming",
          "propagation": "Propagate from bulbs",
          "growingZones": "Suitable for USDA Zones 3-8",
          "nativeHabitat": "Central Asia",
          "uses": "Popular as garden flowers, cut flowers, and for forcing indoors",
          "toxicity": "Non-toxic to humans, but bulbs can be toxic if ingested",
          "pestsAndDiseases": "Generally resistant to pests and diseases, but can be affected by aphids, slugs, and fungal diseases"
        },
        "type": "Outdoor",
        "images": "https://m.media-amazon.com/images/I/71sQOlkixLL.jpg"
      },
      {
        "id": 5,
        "commonName": "Lily",
        "scientificName": "Lilium",
        "description": "Lilies are bulbous perennial flowering plants known for their large, showy flowers and pleasant fragrance. They belong to the Liliaceae family and are native to temperate regions of the Northern Hemisphere.",
        "careRequirements": {
          "light": "Full sun to partial shade",
          "watering": "Regular watering, keeping soil evenly moist but not waterlogged",
          "temperature": "Prefers cool to moderate temperatures",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining soil with good fertility",
          "fertilization": "Feed with balanced fertilizer during the growing season",
          "pruning": "Remove spent flowers and foliage after blooming",
          "propagation": "Propagate from bulbs or seeds",
          "growingZones": "Depends on the variety, but most are suited for USDA Zones 4-9",
          "nativeHabitat": "Temperate regions of the Northern Hemisphere",
          "uses": "Popular as garden flowers, cut flowers, and in floral arrangements",
          "toxicity": "Highly toxic to cats, mildly toxic to dogs and humans if ingested",
          "pestsAndDiseases": "Susceptible to aphids, thrips, and fungal diseases"
        },
        "type": "Outdoor",
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvjoslLCeNwFe6fESZOqgYfTUI9tCpRSweasu6kqK3nw&s"
      },
      {
        "id": 6,
        "commonName": "Geranium",
        "scientificName": "Pelargonium",
        "description": "Geraniums are flowering plants native to South Africa. They are popular ornamental plants grown for their colorful flowers and fragrant foliage. Geraniums are versatile and can be grown in gardens, containers, and hanging baskets.",
        "careRequirements": {
        "light": "Full sun to partial shade",
        "watering": "Regular watering, allowing soil to dry out slightly between waterings",
        "temperature": "Prefers moderate temperatures",
        "humidity": "Tolerates a wide range of humidity levels",
        "soil": "Well-draining soil with moderate fertility",
        "fertilization": "Feed with balanced fertilizer during the growing season",
        "pruning": "Pinch back spent flowers and leggy growth to promote bushiness",
        "propagation": "Propagate from stem cuttings or division",
        "growingZones": "Depends on the variety, but most are suited for USDA Zones 9-11",
        "nativeHabitat": "South Africa",
        "uses": "Popular as bedding plants, container plants, and in hanging baskets",
        "toxicity": "Mildly toxic to humans and pets if ingested",
        "pestsAndDiseases": "Resistant to most pests and diseases, but can be affected by aphids, spider mites, and fungal diseases"
        },
        "type": "Outdoor",
        "images": "https://media.istockphoto.com/id/599751224/photo/red-garden-geranium-flowers-in-pot.jpg?s=612x612&w=0&k=20&c=R3FldsJr6O45zErYgs5IJv0tq9zJ_ualAcwAiS9LbmY="
        },
        {
        "id": 7,
        "commonName": "Hydrangea",
        "scientificName": "Hydrangea",
        "description": "Hydrangeas are deciduous or evergreen shrubs native to Asia and the Americas. They are known for their large, showy flower heads in shades of pink, blue, purple, and white. Hydrangeas are popular ornamental plants in gardens and landscapes.",
        "careRequirements": {
        "light": "Partial shade to full sun, depending on the variety",
        "watering": "Regular watering, keeping soil evenly moist",
        "temperature": "Prefers moderate temperatures",
        "humidity": "Tolerates a wide range of humidity levels",
        "soil": "Well-draining soil with good fertility",
        "fertilization": "Feed with balanced fertilizer in spring",
        "pruning": "Prune after flowering to remove dead wood and shape the plant",
        "propagation": "Propagate from stem cuttings or layering",
        "growingZones": "Depends on the variety, but most are suited for USDA Zones 3-9",
        "nativeHabitat": "Asia and the Americas",
        "uses": "Popular as garden shrubs, cut flowers, and in floral arrangements",
        "toxicity": "Mildly toxic to humans and pets if ingested",
        "pestsAndDiseases": "Resistant to most pests and diseases, but can be affected by aphids, mites, and fungal diseases"
        },
        "type": "Outdoor",
        "images": "https://cdn.britannica.com/21/137521-050-B20FDFCB/Flower-hydrangea-hortensia-French.jpg"
        },
        {
        "id": 8,
        "commonName": "Lavender",
        "scientificName": "Lavandula",
        "description": "Lavender is a fragrant perennial herb native to the Mediterranean region. It is known for its aromatic foliage and spikes of purple, blue, or pink flowers. Lavender is prized for its calming scent and is used in aromatherapy, culinary, and ornamental purposes.",
        "careRequirements": {
        "light": "Full sun",
        "watering": "Moderate watering, allowing soil to dry out slightly between waterings",
        "temperature": "Prefers warm temperatures, drought-tolerant once established",
        "humidity": "Tolerates low humidity levels",
        "soil": "Well-draining soil with low to moderate fertility",
        "fertilization": "Avoid heavy fertilization, as it can reduce fragrance",
        "pruning": "Prune after flowering to promote bushiness and remove spent flowers",
        "propagation": "Propagate from cuttings or seeds",
        "growingZones": "Depends on the variety, but most are suited for USDA Zones 5-9",
        "nativeHabitat": "Mediterranean region",
        "uses": "Popular for its fragrance in sachets, potpourri, cosmetics, and culinary dishes",
        "toxicity": "Non-toxic to humans, but can be toxic to pets if ingested in large quantities",
        "pestsAndDiseases": "Resistant to most pests and diseases, but can be affected by aphids, spider mites, and root rot"
        },
        "type": "Outdoor",
        "images": "https://www.gardendesign.com/pictures/images/263x300Exact_68x0/site_3/english-lavender-lavandula-angustifolia-garden-design_11716.jpg"
        },
        {
        "id": 9,
        "commonName": "Snapdragon",
        "scientificName": "Antirrhinum majus",
        "description": "Snapdragons are colorful annual or perennial flowering plants native to Europe, North Africa, and North America. They are known for their unique, snap-like flowers that resemble the face of a dragon when squeezed. Snapdragons are popular in gardens and floral arrangements.",
        "careRequirements": {
        "light": "Full sun to partial shade",
        "watering": "Regular watering, keeping soil consistently moist but not waterlogged",
        "temperature": "Prefers cool to moderate temperatures",
        "humidity": "Tolerates a wide range of humidity levels",
        "soil": "Well-draining soil with moderate fertility",
        "fertilization": "Feed with balanced fertilizer during the growing season",
        "pruning": "Remove spent flowers to promote continuous blooming",
        "propagation": "Propagate from seeds or stem cuttings",
        "growingZones": "Depends on the variety, but most are suited for USDA Zones 4-10",
        "nativeHabitat": "Europe, North Africa, and North America",
        "uses": "Popular as bedding plants, borders, and in floral arrangements",
        "toxicity": "Non-toxic to humans and pets",
        "pestsAndDiseases": "Resistant to most pests and diseases, but can be affected by aphids, spider mites, and rust"
        },
        "type": "Outdoor",
        "images": "https://cdn.britannica.com/24/235424-050-9E128DEB/Snapdragon-flowers-plant.jpg"
        },
        {
          id: 10,
          "commonName": "Chinese Evergreen",
          "scientificName": "Aglaonema",
          "description": "Chinese Evergreen is a popular indoor plant valued for its attractive foliage and air-purifying qualities. It comes in various cultivars with different leaf patterns and colors, making it a versatile choice for indoor decor.",
          "careRequirements": {
            "light": "Tolerates low to medium indirect light, but prefers indirect light",
            "watering": "Allow soil to dry out slightly between waterings, as overwatering can cause root rot",
            "temperature": "Prefers temperatures between 65-75°F",
            "humidity": "Tolerates average indoor humidity levels",
            "soil": "Well-draining potting mix",
            "fertilization": "Feed with a balanced liquid fertilizer every 4-6 weeks during the growing season",
            "pruning": "Trim yellowing leaves as needed",
            "propagation": "Propagate through division of root ball or stem cuttings",
            "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
            "nativeHabitat": "Native to tropical regions of Asia",
            "uses": "Popular as an indoor decorative plant",
            "toxicity": "Mildly toxic if ingested, can cause irritation",
            "pestsAndDiseases": "Resistant to pests, but may suffer from root rot if overwatered"
          },
          "type": "Indoor",
          "images": "https://cdn.mos.cms.futurecdn.net/opVxtLDKnSymCc3JruP8GK.jpg"
        },
        {
          id: 11,
          "commonName": "Aloe Vera",
          "scientificName": "Aloe vera",
          "description": "Aloe Vera is a succulent plant valued for its medicinal properties and attractive foliage. It is known for its soothing gel, which is commonly used to treat minor burns and skin irritations.",
          "careRequirements": {
            "light": "Prefers bright, indirect light",
            "watering": "Allow soil to dry out between waterings, as overwatering can cause root rot",
            "temperature": "Thrives in temperatures between 60-75°F",
            "humidity": "Tolerates average indoor humidity levels",
            "soil": "Use a well-draining cactus or succulent potting mix",
            "fertilization": "Feed sparingly with a balanced liquid fertilizer during the growing season",
            "pruning": "Remove spent flower stalks and dead leaves",
            "propagation": "Propagate from offsets or leaf cuttings",
            "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
            "nativeHabitat": "Native to the Arabian Peninsula",
            "uses": "Valued for its medicinal properties and as an ornamental plant",
            "toxicity": "Mildly toxic if ingested, can cause stomach discomfort",
            "pestsAndDiseases": "Resistant to pests, but may suffer from root rot if overwatered"
          },
          "type": "Indoor",
          "images":"https://media.post.rvohealth.io/wp-content/uploads/2020/09/aloe-vera-732x549-thumbnail.jpg"
        },
        {
          id: 12,
          "commonName": "Jade Plant",
          "scientificName": "Crassula ovata",
          "description": "The Jade Plant, also known as the Money Plant or Friendship Tree, is a popular succulent valued for its attractive and resilient nature. It is believed to bring good luck and prosperity.",
          "careRequirements": {
            "light": "Prefers bright, indirect light",
            "watering": "Allow soil to dry out between waterings, as overwatering can cause root rot",
            "temperature": "Thrives in temperatures between 65-75°F",
            "humidity": "Tolerates average indoor humidity levels",
            "soil": "Use a well-draining cactus or succulent potting mix",
            "fertilization": "Feed with a balanced liquid fertilizer monthly during the growing season",
            "pruning": "Pinch back stem tips to encourage bushiness",
            "propagation": "Propagate from stem or leaf cuttings",
            "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
            "nativeHabitat": "Native to South Africa",
            "uses": "Popular as a houseplant and for bonsai cultivation",
            "toxicity": "Mildly toxic if ingested, can cause stomach discomfort",
            "pestsAndDiseases": "Resistant to pests, but may suffer from root rot if overwatered"
          },
          "type": "Indoor",
          "images": "https://m.media-amazon.com/images/I/51fehIGF48L._AC_UF1000,1000_QL80_.jpg"
        },
        {
          id: 13,
          "commonName": "Begonia",
          "scientificName": "Begonia",
          "description": "Begonias are a diverse group of flowering plants valued for their colorful flowers and attractive foliage. They come in various forms, including tuberous, fibrous, and rhizomatous, and are popular as both indoor and outdoor plants.",
          "careRequirements": {
            "light": "Prefers bright, indirect light",
            "watering": "Keep soil consistently moist, but not waterlogged",
            "temperature": "Prefers temperatures between 65-75°F",
            "humidity": "Tolerates average indoor humidity levels",
            "soil": "Use a well-draining potting mix rich in organic matter",
            "fertilization": "Feed with a balanced liquid fertilizer every 4-6 weeks during the growing season",
            "pruning": "Remove spent flowers and yellowing leaves",
            "propagation": "Propagate from stem cuttings or leaf cuttings",
            "growingZones": "Depends on the species and variety, but many are suited for indoor cultivation",
            "nativeHabitat": "Native to tropical and subtropical regions worldwide",
            "uses": "Popular as ornamental plants in gardens and indoor spaces",
            "toxicity": "Mildly toxic if ingested, can cause stomach discomfort",
            "pestsAndDiseases": "Susceptible to powdery mildew, aphids, and spider mites"
          },
          "type": "Indoor/Outdoor",
          "images": "https://naturerabbit.in/wp-content/uploads/2018/11/Nature-Rabbit-Begonia-Red-Plant-1.jpg"
        },
        {
          id: 14,
          "commonName": "Kalanchoe",
          "scientificName": "Kalanchoe",
          "description": "Kalanchoes are succulent plants valued for their colorful flowers and thick, fleshy leaves. They are popular as indoor and outdoor plants, especially during the winter months when they produce vibrant blooms.",
          "careRequirements": {
            "light": "Prefers bright, indirect light",
            "watering": "Allow soil to dry out slightly between waterings, as overwatering can cause root rot",
            "temperature": "Thrives in temperatures between 60-85°F",
            "humidity": "Tolerates average indoor humidity levels",
            "soil": "Use a well-draining cactus or succulent potting mix",
            "fertilization": "Feed with a balanced liquid fertilizer monthly during the growing season",
            "pruning": "Remove spent flowers and dead leaves",
            "propagation": "Propagate from stem cuttings or leaf cuttings",
            "growingZones": "Depends on the species and variety, but many are suitable for indoor cultivation",
            "nativeHabitat": "Native to Madagascar and tropical Africa",
            "uses": "Commonly grown indoors as a decorative plant",
            "toxicity": "Mildly toxic if ingested, can cause stomach discomfort",
            "pestsAndDiseases": "Resistant to pests, but may suffer from root rot if overwatered"
          },
          "type": "Indoor/Outdoor",
          "images": "https://rukminim2.flixcart.com/image/850/1000/kwv0djk0/plant-sapling/u/t/f/yes-annual-yes-kalanchoe-plant-indian-flower-1-pagoda-point-original-imag9gdafaytz7gf.jpeg?q=90&crop=false"
        },
        {
          id: 15,
          "commonName": "Bromeliad",
          "scientificName": "Bromeliaceae",
          "description": "Bromeliads are a diverse family of tropical plants valued for their vibrant and long-lasting flowers, as well as their striking foliage. They are popular as indoor and outdoor ornamental plants and are relatively easy to care for.",
          "careRequirements": {
            "light": "Prefers bright, indirect light",
            "watering": "Keep the central cup filled with water and mist the leaves regularly, avoid overwatering the soil",
            "temperature": "Thrives in temperatures between 65-80°F",
            "humidity": "Requires high humidity levels",
            "soil": "Use a well-draining potting mix formulated for epiphytic plants",
            "fertilization": "Feed with a diluted liquid fertilizer monthly during the growing season",
            "pruning": "Trim dead leaves and spent flowers as needed",
            "propagation": "Propagate from offsets produced by the mother plant",
            "growingZones": "Depends on the species and variety, but many are suitable for indoor cultivation",
            "nativeHabitat": "Native to tropical regions of the Americas",
            "uses": "Popular as indoor and outdoor ornamental plants",
            "toxicity": "Non-toxic to humans and pets",
            "pestsAndDiseases": "Generally pest-resistant, but may suffer from fungal diseases if overwatered"
          },
          "type": "Indoor/Outdoor",
          "images": "https://asset.bloomnation.com/c_pad,d_vendor:global:catalog:product:image.png,f_auto,fl_preserve_transparency,q_auto/v1635386596/vendor/2864/catalog/product/2/0/20210824113629_file_6125827d60dad_612582ef2afae._6179a27159724.jpg"
        },
        {
          id: 16,
          "commonName": "Gerbera Daisy",
          "scientificName": "Gerbera jamesonii",
          "description": "Gerbera Daisies are cheerful and colorful flowering plants valued for their large, daisy-like flowers that come in various vibrant hues. They are popular as indoor and outdoor plants and are commonly used in floral arrangements.",
          "careRequirements": {
            "light": "Prefers bright, indirect light",
            "watering": "Keep soil evenly moist, but not waterlogged",
            "temperature": "Prefers temperatures between 65-75°F",
            "humidity": "Tolerates average indoor humidity levels",
            "soil": "Use a well-draining potting mix rich in organic matter",
            "fertilization": "Feed with a balanced liquid fertilizer every 4-6 weeks during the growing season",
            "pruning": "Remove spent flowers and yellowing leaves",
            "propagation": "Propagate from seed or by dividing the clumps",
            "growingZones": "Suitable for outdoor cultivation in USDA Zones 8-11, can be grown indoors",
            "nativeHabitat": "Native to South Africa",
            "uses": "Popular as ornamental plants in gardens and floral arrangements",
            "toxicity": "Non-toxic to humans and pets",
            "pestsAndDiseases": "Susceptible to aphids, spider mites, and powdery mildew"
          },
          "type": "Indoor/Outdoor",
          "images": "https://nurserylive.com/cdn/shop/products/nurserylive-plants-gerbera-red-plant-16968877113484.jpg?v=1634220246"
        },
        {
          id: 17,
          "commonName": "Cyclamen",
          "scientificName": "Cyclamen",
          "description": "Cyclamen is a charming flowering plant known for its uniquely shaped flowers and marbledfoliage. It blooms in the winter months and is popular as an indoor plant for adding color to homes during the colder seasons.",
          "careRequirements": {
            "light": "Prefers bright, indirect light",
            "watering": "Water thoroughly when the top inch of soil feels dry, avoid getting water on the crown of the plant",
            "temperature": "Prefers cool temperatures between 50-65°F",
            "humidity": "Tolerates average indoor humidity levels",
            "soil": "Use a well-draining potting mix",
            "fertilization": "Feed with a balanced liquid fertilizer every 4-6 weeks during the growing season",
            "pruning": "Remove spent flowers and yellowing leaves",
            "propagation": "Propagate from seed or by dividing the tubers",
            "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
            "nativeHabitat": "Native to the Mediterranean region",
            "uses": "Popular as an indoor decorative plant, especially during the winter months",
            "toxicity": "Toxic if ingested, can cause stomach discomfort",
            "pestsAndDiseases": "Susceptible to aphids, spider mites, and gray mold"
          },
          "type": "Indoor",
          "images":"https://imengine.public.prod.dur.navigacloud.com/?uuid=495f6b8c-03d2-5c14-be36-85ffb72df1ef&function=original&type=preview"
        }
   

];
export default Data;