
const Data = [
  {
      id: 0,
      "commonName": "Peace Lily",
      "scientificName": "Spathiphyllum",
      "description": "The Peace Lily is a popular indoor plant known for its elegant white flowers and glossy green leaves. It thrives in low light conditions and is relatively easy to care for.",
      "careRequirements": {
        "light": "Low to medium indirect light",
        "watering": "Keep soil consistently moist, but avoid overwatering",
        "temperature": "Prefers temperatures between 65-80°F",
        "humidity": "Enjoys high humidity levels",
        "soil": "Well-draining potting mix rich in organic matter",
        "fertilization": "Feed monthly with a balanced liquid fertilizer during the growing season",
        "pruning": "Remove dead or yellowing leaves as needed",
        "propagation": "Propagate through division of plant clumps or by rooting stem cuttings",
        "growingZones": "Suitable for USDA Zones 10-11 outdoors, often grown indoors",
        "nativeHabitat": "Native to tropical regions of the Americas and southeastern Asia",
        "uses": "Popular as an indoor decorative plant for homes and offices",
        "toxicity": "Mildly toxic if ingested, can cause irritation",
        "pestsAndDiseases": "Resistant to pests but susceptible to root rot if overwatered"
      },
      "images":'https://static.vecteezy.com/system/resources/previews/037/501/544/original/ai-generated-peace-lily-spathiphyllum-wallisii-flower-isolated-on-transparent-background-png.png',
      "type": "Indoor",
      
    },
    {
      id: 1,
      "commonName": "African Violet",
      "scientificName": "Saintpaulia",
      "description": "African Violets are charming indoor plants valued for their delicate, colorful flowers and fuzzy leaves. They are relatively low-maintenance and can bloom year-round when provided.",
      "careRequirements": {
        "light": "Bright, indirect light",
        "watering": "Water when the top inch of soil feels dry, avoid getting water on the leaves",
        "temperature": "Prefers temperatures between 65-75°F",
        "humidity": "Does well in average indoor humidity levels",
        "soil": "Use a well-draining, slightly acidic potting mix",
        "fertilization": "Feed with a balanced fertilizer every 4-6 weeks during the growing season",
        "pruning": "Remove spent flowers and yellowing leaves to encourage blooming",
        "propagation": "Propagate from leaf cuttings or offsets",
        "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
        "nativeHabitat": "Native to Tanzania",
        "uses": "Commonly grown indoors as a decorative houseplant",
        "toxicity": "Non-toxic to humans and pets",
        "pestsAndDiseases": "Susceptible to aphids, spider mites, and powdery mildew"
      },
      "type": "Indoor",
      "images":'https://png.pngtree.com/png-clipart/20230916/original/pngtree-the-flower-pot-sticker-is-purple-with-purple-flowers-clipart-vector-png-image_12251441.png',
    },
    {
      id: 2,
      "commonName": "Orchid",
      "scientificName": "Orchidaceae",
      "description": "Orchids are a diverse family of flowering plants known for their stunning and exotic blooms. They come in various colors, shapes, and sizes, and are prized for their elegance and beauty.",
      "careRequirements": {
        "light": "Bright, indirect light",
        "watering": "Water sparingly, allowing the potting mix to dry slightly between waterings",
        "temperature": "Prefers temperatures between 60-80°F",
        "humidity": "Requires high humidity levels, misting may be necessary",
        "soil": "Use a well-draining orchid potting mix, such as bark or sphagnum moss",
        "fertilization": "Feed with a specialized orchid fertilizer according to label instructions",
        "pruning": "Remove spent flowers and trim damaged or yellowing leaves",
        "propagation": "Propagation is typically done through division or from keiki (baby plants)",
        "growingZones": "Depends on the orchid variety, many are suited for indoor cultivation",
        "nativeHabitat": "Orchids are found in diverse habitats worldwide, from tropical rainforests to arctic tundras",
        "uses": "Valued as ornamental plants, often grown indoors in pots or mounted on slabs",
        "toxicity": "Non-toxic to humans and most pets",
        "pestsAndDiseases": "May be susceptible to aphids, scale insects, and fungal diseases if not properly cared for"
      },
      "type": "Indoor",
      "images":'https://static.vecteezy.com/system/resources/previews/027/254/707/original/white-orchid-plant-in-a-white-pot-png.png',
    },
    {
      id: 3,
      "commonName": "Snake Plant",
      "scientificName": "Sansevieria trifasciata",
      "description": "The Snake Plant, also known as Mother-in-Law's Tongue, is a hardy and low-maintenance indoor plant characterized by its upright sword-like leaves. ",
      "careRequirements": {
        "light": "Tolerates low to bright indirect light, but prefers indirect light",
        "watering": "Allow soil to dry between waterings, as overwatering can cause root rot",
        "temperature": "Thrives in temperatures between 60-85°F",
        "humidity": "Tolerates average indoor humidity levels",
        "soil": "Well-draining potting mix, can tolerate various soil types",
        "fertilization": "Feed sparingly with a balanced liquid fertilizer during the growing season",
        "pruning": "Trim yellowing leaves as needed",
        "propagation": "Propagate through division of rhizomes or leaf cuttings",
        "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
        "nativeHabitat": "Native to West Africa",
        "uses": "Popular as a low-maintenance indoor plant and for its air-purifying qualities",
        "toxicity": "Mildly toxic if ingested, can cause stomach discomfort",
        "pestsAndDiseases": "Resistant to pests, but may suffer from root rot if overwatered"
      },
      "type": "Indoor",
      "images":'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ8KleJ1SPIUMO-XPblXPVFbOkC_nxZZm8BaP9pezOG3-Q99q2o',
    },
    {
      id: 4,
      "commonName": "Dieffenbachia",
      "scientificName": "Dieffenbachia",
      "description": "Dieffenbachia, also known as Dumb Cane, is a popular indoor plant valued for its attractive foliage and air-purifying qualities. It features large, broad leaves with striking .",
      "careRequirements": {
        "light": "Prefers bright, indirect light",
        "watering": "Keep soil consistently moist during the growing season, but allow it to dry out slightly between waterings in winter",
        "temperature": "Prefers temperatures between 65-75°F",
        "humidity": "Tolerates average indoor humidity levels",
        "soil": "Use a well-draining potting mix rich in organic matter",
        "fertilization": "Feed with a balanced liquid fertilizer monthly during the growing season",
        "pruning": "Trim yellowing leaves and remove dust from the foliage regularly",
        "propagation": "Propagate through stem cuttings",
        "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
        "nativeHabitat": "Native to tropical regions of Central and South America",
        "uses": "Popular as an indoor decorative plant",
        "toxicity": "Toxic if ingested, can cause irritation and swelling of the mouth and throat",
        "pestsAndDiseases": "Resistant to pests, but may suffer from leaf spots if overwatered"
      },
      "images":'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRU4MHX6lxNq29lA3k9CaGhFLqI3RC7Cpnl3xPDZgyxJv6Sftx4',
    },
    {
      id:5,
      "commonName": "Boston Fern",
      "scientificName": "Nephrolepis exaltata",
      "description": "The Boston Fern is a classic and popular indoor plant known for its lush, feathery fronds that cascade gracefully from hanging baskets or pots. It thrives in humid environments and adds a touch of greenery to indoor spaces.",
      "careRequirements": {
        "light": "Prefers bright, indirect light but can tolerate lower light conditions",
        "watering": "Keep soil consistently moist, but not waterlogged",
        "temperature": "Thrives in temperatures between 60-75°F",
        "humidity": "Requires high humidity levels, misting may be necessary",
        "soil": "Well-draining potting mix with high organic content",
        "fertilization": "Feed with a balanced liquid fertilizer every 4-6 weeks during the growing season",
        "pruning": "Remove dead or yellowing fronds as needed",
        "propagation": "Propagate through division of the root ball",
        "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
        "nativeHabitat": "Native to tropical regions of the Americas",
        "uses": "Commonly grown indoors as a decorative houseplant, often in hanging baskets",
        "toxicity": "Non-toxic to humans and pets",
        "pestsAndDiseases": "Susceptible to spider mites, scale insects, and mealybugs"
      },
      "type": "Indoor",
      "images": "https://res.cloudinary.com/patch-gardens/image/upload/c_fill,f_auto,h_840,q_auto:good,w_840/v1539018609/products/boston-fern-8f6ed2.psd"
    },
    {
      id: 6,
      "commonName": "Christmas Cactus",
      "scientificName": "Schlumbergera",
      "description": "The Christmas Cactus is a popular holiday plant known for its colorful flowers that bloom around Christmas time. It is a type of succulent that requires minimal care and can thrive indoors.",
      "careRequirements": {
        "light": "Prefers bright, indirect light",
        "watering": "Water thoroughly when the top inch of soil feels dry, but avoid overwatering",
        "temperature": "Prefers temperatures between 60-70°F",
        "humidity": "Tolerates average indoor humidity levels",
        "soil": "Well-draining potting mix formulated for succulents",
        "fertilization": "Feed with a balanced liquid fertilizer monthly during the growing season",
        "pruning": "Pinch back stems after flowering to encourage bushiness",
        "propagation": "Propagate from stem cuttings",
        "growingZones": "Suitable for indoor cultivation, not cold-hardy outdoors",
        "nativeHabitat": "Native to Brazil",
        "uses": "Grown indoors as a decorative plant, especially during the holiday season",
        "toxicity": "Non-toxic to humans and pets",
        "pestsAndDiseases": "Generally pest-resistant, but may suffer from root rot if overwatered"
      },
      "type": "Indoor",
      "images": "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-christmas-cactus-schlumbergera-succulent-plant-1-723302_300x@2x.jpg?v=1679749533"
    }
];
export default Data;